name: Build deb Package
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/deps
        key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt') }}
        
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          debhelper \
          devscripts \
          fakeroot \
          git \
          gcc-9 \
          g++-9 \
          clang-10 \
          pkg-config \
          python3 \
          ocl-icd-dev \
          libegl1-mesa-dev \
          ocl-icd-opencl-dev \
          libdrm-dev \
          libxfixes-dev \
          libxext-dev \
          llvm-10-dev \
          libclang-10-dev \
          libtinfo-dev \
          libedit-dev \
          zlib1g-dev
        mkdir -p ~/deps
        
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake -DLLVM_INSTALL_DIR=/usr/lib/llvm-10 -DCOMPILER=GCC ../
        
    - name: Build the driver
      run: |
        cd build
        make
        make utest
        
    - name: Package the driver
      run: |
        cd build
        make install
        make package
        
    - name: Upload the package
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: build/*.deb
