name: Build deb Package
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          debhelper \
          devscripts \
          fakeroot \
          git \
          gcc-9 \
          g++-9 \
          clang
        
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake -DCOMPILER=GCC ../
        
    - name: Build the driver
      run: |
        cd build
        make
        make utest
        
    - name: Package the driver
      run: |
        cd build
        make install
        make package
        
    - name: Upload the package
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: build/*.deb
